wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.19
    start_time: 1727492167.590046
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.13.4
      8:
      - 5
alpha:
  desc: null
  value: 0.005
b:
  desc: null
  value: 5
base_method:
  desc: null
  value: mle
batch_size:
  desc: null
  value: 100
carr_id:
  desc: null
  value: 1
delta:
  desc: null
  value: null
discount:
  desc: null
  value: 0.9
env_name:
  desc: null
  value: bus_engine
epoch_size:
  desc: null
  value: 10000
hidden_size:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.004
log_dir:
  desc: null
  value: data
method:
  desc: null
  value: our
n_a:
  desc: null
  value: 2
n_sample:
  desc: null
  value: 5000
n_states_aggregated:
  desc: null
  value: 5
n_steps:
  desc: null
  value: 100
patience:
  desc: null
  value: 5
reward_type:
  desc: null
  value: linear
seed:
  desc: null
  value: 0
theta:
  desc: null
  value:
  - 1
  - 0
  - 0
theta_0:
  desc: null
  value:
  - 0.5
  - 0.5
  - 0.5
